### ISSUE TITLE
NonTiledLayer

### ISSUE THREAD

**Issue by bambryan** [socib/Leaflet.TimeDimension#179]
I have changed my layers into nonTiledLayers and I get this error.  Not sure why it doesn't work for me but on your examples it works just fine.

TypeError: this._baseLayer.getURL is not a function. (In 'this._baseLayer.getURL()', 'this._baseLayer.getURL' is undefined)

TypeError: this._baseLayer.setLoaded is not a function. (In 'this._baseLayer.setLoaded(true)', 'this._baseLayer.setLoaded' is undefined)

**Comment by krisaoe** [comment]
Hi @bambryan, did you find out what caused this? I'm seeing the same errors when using TimeDimension with nonTiledLayers

**Comment by bambryan** [comment]
No I moved away from nonTiledLayers with my project.

**Comment by pedroetb** [comment]
@krisaoe @bambryan I was seeing this error too.

The root cause is importing `nonTiledLayers` after `timeDimension`, because `timeDimension` will alter `nonTiledLayers` definitions to meet its needs (check at <https://github.com/socib/Leaflet.TimeDimension/blob/master/src/leaflet.timedimension.layer.wms.js#L406>).

If you guarantee that `nonTiledLayers` is loaded before `timeDimension`, instances from `L.NonTiledLayer.WMS` will have available the properties and methods that you are missing.
