### ISSUE TITLE
Support for geometrycollections?

### ISSUE THREAD

**Issue by syre** [socib/Leaflet.TimeDimension#47]
Is there support for GeometryCollections and not just a single Geometry for GeoJSON formatting?

**Comment by bielfrontera** [comment]
Hi @syre ,
can you share an example of geojson that you are planning to visualize with timedimension?

I've created this [jsfiddle](http://jsfiddle.net/bielfrontera/5afucs89/) with a geojson composed by two GeometryCollections. Each one, has a different time property, at geometrycollection level, not for each geometry.

In order to make it work,  I have extended TimeDimension.Layer.GeoJson, to override `_getFeatureBetweenDates` method. It shows the feature if the time attribute its inside current time range (according to current time and duration).

If you have the time attribute at geometry level, you should modify this method, that can return a new geometryCollection with those geometries that are active at the current time. You might also have to override `_getFeatureTimes`, in order to get time values from geometries, and not from feature properties.
