### ISSUE TITLE
Wrong fps label

### ISSUE THREAD

**Issue by jekuno** [socib/Leaflet.TimeDimension#49]
When displaying the speed slider the knob has a middle position (10fps), but the label shows "1fps". The correct value is displayed as soon as I move the slider manually.

Tested with the following values:
```
transitionTime: 100
minSpeed:      0.1
maxSpeed:      20
```

**Comment by ram-one** [comment]
Can you post your code or a jsbin ?

**Comment by jekuno** [comment]
I added an example to the JSBin playground: http://playground-leaflet.rhcloud.com/vor/1/edit?html,output
I didn't add any times - the effect is the same with or without data.

The relevant lines of code are at the very end.

**Comment by ram-one** [comment]
Ok this is because the initial speed is guessed from playerOptions. But with manual intantiation, you don't have that speed.

If you add
```
       playerOptions:{transitionTime: 100}
```
it works...

This bug also appear if the player speed is changed programmatically
The label should be updated with the speed when the player changes. For now, it's only updated when the user slide the knob.

**Comment by jekuno** [comment]
:+1:
