### ISSUE TITLE
TimeDimension compatibility with Leaflet 1.0 beta 1

### ISSUE THREAD

**Issue by ClaudioCas** [socib/Leaflet.TimeDimension#5]
Dear developer,
thanks a lot for your great plugin. 
Do you plan to add support for Leaflet 1.0 beta 1 to TimeDimension?
I try to upgrade the js in your example but I give an "callback not define" error in javascript into the main leaflet code.
Thanks a lot
Claudio

**Comment by bielfrontera** [comment]
Hi Claudio,
thanks for your comment. 

I've checked the plugin with leaflet-1.0.0-b1, and I get the same error, provoked because the custom layer implemented in TimeDimension does not have the method `_layerAdd`. According to the [new documentation](http://mourner.github.io/Leaflet/reference.html#layer), now custom layers should extend `L.Layer` instead of `L.Class`.

So, I've changed 
```javascript
L.TimeDimension.Layer = L.Class.extend({
```
by
```javascript
var baseClass = L.Layer || L.Class;
L.TimeDimension.Layer = baseClass.extend({
```
in https://github.com/socib/Leaflet.TimeDimension/blob/master/src/leaflet.timedimension.layer.js#L8, and our examples seem to work fine with leaflet-1.0.0-b1 and leaflet-0.7.3.

I will commit the changes in a few days, but I'm not sure this is the best solution to work with old and new releases of Leaflet. @mourner, could you give us some advice? Thanks!

**Comment by mourner** [comment]
`(L.Layer || L.Class).extend(...)` is how I did this in my own plugins :)

**Comment by ClaudioCas** [comment]
Thanks a lot. The patch works great and thanks for update the library!
