### ISSUE TITLE
setTimeout isn't what is expected

### ISSUE THREAD

**Issue by hflsmax** [socib/Leaflet.TimeDimension#72]
In the class setCurrentTimeIndex, setTimeout is used to prevent layers from not responding (line 95). However what setTimeout do is that it wait specified time and then execute the function, which is not what is wanted here.

**Comment by r1m** [comment]
This method asks the layer to load a specific time. Then we set a timeout to check after xx seconds if the layer has successfully loaded this time. If not, we consider it loaded anyway. Because we don't want to wait forever.

Please specify the behavior your are expecting. You can change the timeout duration in options.
