### ISSUE TITLE
question on example 9

### ISSUE THREAD

**Issue by xhx509** [socib/Leaflet.TimeDimension#75]
Hi 
Your example 9 is very helpful to me.  However, there is small problem I can not solve. When I selected both 'Gpx Layer' and 'KML Layer' , the time slider player could only show either 'GPx Layer' time period or 'KML Layer' time period. I want slider player to show both time periods(from earliest time of both layer to latest time of both layer) or set start time and end time .  What should I do?

Thanks in advance. 

Xavier

**Comment by bielfrontera** [comment]
Hi @xhx509 (Xavier),
you can change this behaviour using `updateTimeDimensionMode` option when creating the TD.geoJson layer. Try with `union` as value, instead of `extremes` which is the default for geoJson.

But I think it could be useful to change these options, in order to be able to make the operations union, replace and intersect with time extremes.

I mean that, now, `union`, `replace` and `intersect` take all the values of available times (current available times and new available times to apply), and operate them to get the new list of available times. Meanwhile, for `extremes`, it takes only the min and max time from the new list of available times, and then, generates a new list of times using the `period` option. So, I can extend the options to be able to work with min and max values and period option, and operation with these min and max time extremes.

**Comment by xhx509** [comment]
Hi @bielfrontera 

I followed your information. Your explanation is very helpful to me.

Wonderful examples.
Thanks a lot.
